version: '3.7'
services:
  php:
    build: php
    ports: ['9000:9001']
    volumes:
      - ./:/var/www/symfony:cached
  nginx:
    build: nginx
    ports: ['80:80']
    links:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ./:/var/www/symfony:cached